apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-epam
  labels:
    app: myapp-epam
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp-epam
  template:
    metadata:
      labels:
        app: myapp-epam
    spec:
      containers:
      - name: liveness
        image: k8s.gcr.io/busybox
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: epam-volume
          mountPath: /app
      volumes:
      - name: epam-volume
        emptyDir: {}    



