apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deploy
  name: my-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-deploy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - mountPath: "/var/www/html"
          name: task
      volumes:
        - name: task
          persistentVolumeClaim:
            claimName: task-pv-claim      

